before_install:
  - sudo apt-get update
  - sudo apt-get install swig

language: python
python:
  - "3.9"
# Command to install dependencies
install:
  - pip install -r requirements.txt
# Command to run tests
script:
  - python -m unittest discover -v -s test
