before_install:
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:ondrej/nginx-mainline
  - sudo apt-get update
  - sudo apt-get install -y openssl libssl-dev
  - sudo apt-get install -y swig  # Add this line to install SWIG

language: python
python:
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover -v -s test
