activation_fn: relu
ent_coef: 3.411778370358421e-05
gae_lambda: 0.92
gamma: 0.98
learning_rate: 1.0571801760716138e-05
lr_schedule: constant
max_grad_norm: 0.3
n_steps: 64
net_arch: small
normalize_advantage: false
ortho_init: false
use_rms_prop: true
vf_coef: 0.22539996708777968
