name: run unittests
on: ["push"]
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install Torch and CUDA
        run: |
          pip install -U pip
          pip install torch==2.1.1+cu121 -f https://download.pytorch.org/whl/torch_stable.html
      - name: Install dependencies
        run: pip install -r requirements.txt
      - run: python -m unittest discover -v -s test
